const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const path = require('node:path');
const html = fs.readFileSync(path.join(__dirname, '../demo/TrackBite-Demo.html'), 'utf8');
const nodes = {}, listeners = {};
const document = { getElementById: id => nodes[id] ??= {value:'',setAttribute(k,v){this[k]=v;}}, addEventListener:(e,f)=>listeners[e]=f };
const context = {document,console};
vm.createContext(context);
vm.runInContext(html.match(/<script>([\s\S]*?)<\/script>/)[1],context);
const run = code => vm.runInContext(code,context);
run("selectState('empty')");
assert.equal(nodes.weight.textContent,100);
assert.equal(nodes.gross.textContent,'100 g');
assert.equal(nodes.net.textContent,'0 g');
assert.equal(nodes.identify.disabled,true);
run("selectState('food')");
assert.equal(nodes.weight.textContent,40);
assert.equal(nodes.gross.textContent,'140 g');
assert.equal(nodes.net.textContent,'40 g');
nodes.navEntry.onclick();
assert.equal(nodes.entryContent.hidden,true);
nodes.save.onclick();
assert.equal(run('meals.length'),0);
nodes.identify.onclick();
assert.equal(nodes.reviewPanel.hidden,false);
nodes.confirm.onclick();
assert.equal(nodes.entryPanel.hidden,false);
assert.equal(nodes.totalEnergy.textContent,'20');
nodes.mealName.value='';
nodes.save.onclick();
assert.equal(run('meals.length'),0);
nodes.mealName.value='Afternoon snack';
for(const invalid of ['','-1','Infinity','NaN']) {
  nodes.energy.value=invalid;nodes.save.onclick();assert.equal(run('meals.length'),0);
}
nodes.energy.value='100';nodes.energy.oninput();
assert.equal(nodes.totalEnergy.textContent,'40');
nodes.entryFoodName.value='<img src=x onerror=alert(1)>';
nodes.save.onclick();
assert.equal(run('meals.length'),1);
assert.equal(nodes.logPanel.hidden,false);
assert.match(nodes.historyRows.innerHTML,/&lt;img/);
assert.doesNotMatch(nodes.historyRows.innerHTML,/<img/);
nodes.save.onclick();
assert.equal(run('meals.length'),1);
nodes.newPortion.onclick();
assert.equal(nodes.weight.textContent,100);
assert.equal(run('meals.length'),1);
nodes.navLog.onclick();
assert.equal(nodes.logContent.hidden,false);
run("selectState('food')");nodes.identify.onclick();nodes.confirm.onclick();nodes.save.onclick();
assert.equal(run('meals.length'),2);
assert.equal(run('meals[0].values[0]'),50);
for(const data of ['{gross:90,tare:100}','{gross:NaN,tare:0}','{gross:Infinity,tare:0}','{gross:100,tare:-1}'])assert.throws(()=>run('netReading('+data+')'));
listeners.keydown({key:'1'});assert.equal(nodes.weight.textContent,100);
listeners.keydown({key:'2',target:{tagName:'INPUT'}});assert.equal(nodes.weight.textContent,100);
listeners.keydown({key:'2'});assert.equal(nodes.weight.textContent,40);
assert.match(html,/connect-src 'none'/);
assert.doesNotMatch(html,/getUserMedia|fetch\(|XMLHttpRequest|https?:\/\//);
console.log('PASS: empty 100/100/0 and food 140/100/40 arithmetic');
console.log('PASS: identification → confirmation → editable meal → saved session history');
console.log('PASS: names/nutrients validated, edits recalculate, duplicate save prevented');
console.log('PASS: history survives new portions; rendered names are escaped');
console.log('PASS: invalid readings rejected, keyboard typing preserved, offline restrictions');
